webapp/Models/ErrorViewModel.cs
using System;

namespace webapp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

webapp/Models/MinecraftContext.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace webapp.Models
{
    public static class MinecraftContext
    {
        private static HttpClient client = new HttpClient();

        public async static Task<MinecraftEvent> GetMinecraftServerStatisticsAsync(MinecraftServer server)
        {
            var endpoint = server.Endpoints.Find(x => x.Name.Contains("rcon"));
            return await GetMinecraftServerStatisticsAsync(endpoint.Address);
        }

        public async static Task<MinecraftEvent> GetMinecraftServerStatisticsAsync(string address)
        {
            var ipaddress = address.Substring(0, address.IndexOf(":"));
            var url = $"https://mcapi.us/server/status?ip={ipaddress}";
            var response = await client.GetAsync(url);
            var responseFromServer = await response.Content.ReadAsStringAsync();
            var minecraftEvent = JsonConvert.DeserializeObject<MinecraftEvent>(responseFromServer);
            return minecraftEvent;
        }

        public async static Task<bool> DeleteMinecraftServer(string name)
        {
            try{
                string url = $"https://hectagonminecraftfunctions.azurewebsites.net/api/DeleteMinecraftServer?name={name}";
                var response = await client.GetAsync(url);
                if(response.IsSuccessStatusCode)
                    return true;
                else
                    return false;
            } catch {
                return false;
            }
        }

        public async static Task<bool> CreateMinecraftServer()
        {
            try{
                //string url = "https://hectagonminecraftfunctions.azurewebsites.net/api/CreateMinecraftServer";
                string url = "https://localhost:44359/api/MinecraftServer";
                var response = await client.PostAsync(url, null);
                if(response.IsSuccessStatusCode)
                    return true;
                else
                    return false;
            } catch{
                return false;
            }
        }

        public async static Task<List<MinecraftServer>> GetMinecraftServerListAsync()
        {
            var jsonserverlist = await GetMinecraftServerListFromAPIAsync();
            var serverlist = JsonConvert.DeserializeObject<List<MinecraftServer>>(jsonserverlist);
            return serverlist;
        }

        private async static Task<string> GetMinecraftServerListFromAPIAsync()
        {
            try
            {
                //string url = "https://hectagonminecraftfunctions.azurewebsites.net/api/GetMinecraftServerList";
                string url = "https://localhost:44359/api/MinecraftServer";
                //client.DefaultRequestHeaders.Add("Accept", "application/json");
                var response = await client.GetAsync(url);
                return await response.Content.ReadAsStringAsync();
            } catch (Exception)
            {
                return null;
            }
        }

        public static List<MinecraftServer> GetHardCodedMinecraftServerList()
        {
            return new List<MinecraftServer>() 
            {
                new MinecraftServer()
                {
                    Name = "tenant1",
                    Endpoints = new List<MinecraftServerEndpoint>() {
                        new MinecraftServerEndpoint() {
                            Name = "minecraft",
                            Address = "123.1.1.1:2557"
                        },
                        new MinecraftServerEndpoint() {
                            Name = "rcon",
                            Address = "123.1.1.1:2558"
                        }
                    }
                },
                new MinecraftServer()
                {
                    Name = "tenant2",
                    Endpoints = new List<MinecraftServerEndpoint>() {
                        new MinecraftServerEndpoint() {
                            Name = "minecraft",
                            Address = "123.1.1.2:2557"
                        },
                        new MinecraftServerEndpoint() {
                            Name = "rcon",
                            Address = "123.1.1.2:2558"
                        }
                    }
                }
            };
        }
    }
}

webapp/Models/MinecraftEvent.cs
using System;

namespace webapp.Models
{
    public class MinecraftEvent
    {
        public string status;
        public bool online;
        public string motd;
        public string error;
        public PlayerInfo players;
        public ServerInfo server;
        public string last_online;
        public string last_updated;
        public string duration;
    }

    public class PlayerInfo
    {
        public string max;
        public string now;
    }

    public class ServerInfo
    {
        public string name;
        public Double protocol;
    }
}

webapp/ViewModels/MinecraftServerStatsViewModel.cs
using System;
using System.Collections.Generic;
using webapp.Models;

namespace webapp.ViewModels
{
    public class MinecraftServerStatsViewModel
    {
        public MinecraftEvent Statistics;
    }
}

webapp/ViewModels/MinecraftServerViewModel.cs
using System;
using System.Collections.Generic;
using webapp.Models;

namespace webapp.ViewModels
{
    public class MinecraftServerViewModel
    {
        public List<MinecraftServer> MinecraftServers;
    }
}

webapp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using webapp.Models;

namespace webapp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

webapp/Controllers/MinecraftServerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using webapp.Models;
using webapp.ViewModels;

namespace webapp.Controllers
{
    public class MinecraftServerController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var viewmodel = await RefreshMinecraftServerViewModel();
            return View(viewmodel);
        }

        private async Task<MinecraftServerViewModel> RefreshMinecraftServerViewModel()
        {
            var viewmodel = new MinecraftServerViewModel();
            viewmodel.MinecraftServers = await MinecraftContext.GetMinecraftServerListAsync();
            return viewmodel;    
        }

        public async Task<IActionResult> Create()
        {
            if(await MinecraftContext.CreateMinecraftServer())
                ViewData["Message"] = "Minecraft server is created.";
            else
                ViewData["Messsage"] = "Error creating minecraft server...";
            return View();
        }

        public async Task<IActionResult> Delete(string id)
        {
            if(await MinecraftContext.DeleteMinecraftServer(id))
                ViewData["Message"] = $"Minecraft server {id} is deleted.";
            else
                ViewData["Messsage"] = $"Error deleting minecraft server {id}...";
            return View();
        }

        public async Task<IActionResult> Details(string id)
        {
            var serverviewmodel = await RefreshMinecraftServerViewModel();
            var server = serverviewmodel.MinecraftServers.Find(x => x.Name.Contains(id));
            var statsviewmodel = new MinecraftServerStatsViewModel();
            statsviewmodel.Statistics = await MinecraftContext.GetMinecraftServerStatisticsAsync(server);
            return View(statsviewmodel);
        }
    }
}

webapp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

webapp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

webapp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/minecraft1.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Noone knows minecraft like Table 17!
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/minecraft3.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Obviously not including the team that wrote it
                </p>
            </div>
        </div>
     </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

webapp/Views/MinecraftServer/Create.cshtml
@{
    ViewData["Title"] = "Minecraft Server";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

webapp/Views/MinecraftServer/Delete.cshtml
@{
    ViewData["Title"] = "Delete Minecraft Server...";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

webapp/Views/MinecraftServer/Index.cshtml
@{
    ViewData["Title"] = "Minecraft Server Page";
}

@model webapp.ViewModels.MinecraftServerViewModel;


          <h2 class="sub-header">Minecraft Servers</h2>
          <div class="table-responsive">
            <table class="table table-striped">
            <thead>
                <tr>
                     <th>
                        Instance Name
                    </th>
                    <th>
                        Minecraft Link
                    </th>
                    <th>
                        RCon Link
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var server in Model.MinecraftServers)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => server.Name)
                        </td>
                         <td>
                            @String.Concat(server.Endpoints[0].Name," - ", server.Endpoints[0].Address)
                        </td> 
                            <td>                                       
                            @String.Concat(server.Endpoints[1].Name," - ", server.Endpoints[1].Address)
                        </td> 

                        <td>    
                            <a asp-controller="MinecraftServer"  asp-action="Delete" asp-route-id="@server.Name">[Delete]</a>
                       </td>
                    </tr>
                }
            </tbody>
        </table>

webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webapp</title>

        <link rel="stylesheet" href="~/css/bootstrap.min.css" />
        <link href="~/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
        <link rel="stylesheet" href="~/css/dashboard.css" asp-append-version="true" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Hack17 Minecraft-a-thon</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
             <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
             <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
             <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>
<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
             <li><a asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a></li>
            <li><a asp-area="" asp-controller="MinecraftServer" asp-action="Index">List Servers</a></li>
            <li><a asp-area="" asp-controller="MinecraftServer" asp-action="Create">Create Server</a></li>
            <li><a asp-area="" asp-controller="MinecraftServer" asp-action="Delete">Delete Server</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div class="container body-content">
        @RenderBody()
        <hr />

    </div> 
        </div>
             </div>
      </div>
    </div>
        <footer>
            <p>&copy; 2018 - webapp</p>
        </footer>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/ie10-viewport-bug-workaround.js"></script>
    


    @RenderSection("Scripts", required: false)
</body>

</html>